import Head from "next/head";

interface MyComponentProps {
    children: React.ReactNode;
    title: string;
}

export default function Layout({ children, title }: MyComponentProps) {
    return (
      <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
      </>
    )
  }